### ISSUE TITLE
Only text highlighting works

### ISSUE THREAD

**Issue by iamkucuk** [chrispahm/linter-gams#26] opened 2019-03-28 12:14 UTC
Hello, first of all, thanks for that wonderful work!

I installed your plugin, however, only code completion and highlighting work. I can't see sets in gams view or error highlighting is not working. Is it the expected behaviour?

Gams version: 23.9

**Comment by chrispahm** [comment] 2019-03-28 16:56
Hey @iamkucuk,
Thanks for raising an issue!
That definitely does not sound like the desired behavior. Can you do me a favor and open the Atom Developer Console (ctrl-shift-i) and Check if you got any red logs in there?
Best Christoph

**Comment by iamkucuk** [comment] 2019-03-28 17:10
![image](https://user-images.githubusercontent.com/41182845/55177927-6ea82100-5195-11e9-8c4f-26d4db5779d3.png)

Here is the errors I'm getting from developer console.

**Comment by chrispahm** [comment] 2019-03-28 17:22
Alright, that means the file gams creates to show where errors occur can’t be found. I’ll try to investigate and let you know once I found something.

**Comment by iamkucuk** [comment] 2019-03-28 18:22
> 
> 
> Alright, that means the file gams creates to show where errors occur can’t be found. I’ll try to investigate and let you know once I found something.

In the meantime, can I help you in any way?

**Comment by iamkucuk** [comment] 2019-03-28 19:23
Tried with the latest version of gams (26.1) still with no luck.

**Comment by chrispahm** [comment] 2019-03-29 09:47
Hey there,

I was fiddling around with it, and could only reproduce the error you are receiving when I "broke" my GAMS installation. There definitely is a reporting issue in `linter-gams` about this, so if you could do the following, it would help me a lot (and also you :) ):

Open up a Windows Explorer window and navigate to the following folder:
```
%USERPROFILE%\.atom\packages\linter-gams\lib
```
In that folder, open the file `linter.js`
After line 61, before the line that starts with 
```js
const gamsProcess = ...
```
Please paste the following
```js
console.log(`${config.gamsexe} "${config.filePath}" lo=3 a=c fileStem=${randStr} o="${config.scratchdir}${path.sep}${randStr}.lst" fErr="${config.scratchdir}${path.sep}${randStr}.err" ${dumpOpt} rf="${config.scratchdir}${path.sep}${randStr}.ref" -scrdir="${config.scratchdir}" -workdir="${config.directory}" -curDir="${config.directory}" ${parameters}`)
```

Now, reload your Atom window (ctrl-shift-p and then type "reload"). In the developer console, you will now see how `linter-gams` tries to call your GAMS installation on your PC through a command line shell:

![dev](https://user-images.githubusercontent.com/20703207/55223968-b4093480-520f-11e9-8884-6897dbcfc74a.png)

Please copy that log output, and paste it into a Windows Comand Line Shell (Windowsbutton + R, then type CMD and hit enter):

![image](https://user-images.githubusercontent.com/20703207/55223923-96d46600-520f-11e9-98ef-0adc815e27bb.png)

It will definitely throw an error there (otherwise `linter-gams` should be working), and it would be really helpful if you could share a screenshot of the error you are receiving!
Best
Christoph

P.S: Sorry that this may take a couple of minutes, but you're helping the community :)

**Comment by iamkucuk** [comment] 2019-03-29 10:35
Sure, I'm glad to help you and the community :)

Here is the output what you asked for:

![image](https://user-images.githubusercontent.com/41182845/55227025-72848380-5227-11e9-97b2-0348dc0f9421.png)

**Comment by chrispahm** [comment] 2019-03-29 10:47
Alright, I was expecting it's the `fileStem` option, because at this very moment we are experiencing the same error on a computer with GAMS 24.4.
I hope that option can be safely deleted, I will do some test and then publish an update.

The following things are likley to change
- The fileStem option: It looks like this was introduced with GAMS 25.0, so removing it should resolve your issue
- There was a small typo: Usually in scenarios like this, you should see a popup window where it shows you the error that you see in the console screenshot you appended above. That typo was making sure that popup never displays
- I rewrote the code that searches for GAMS installations on your computer, that should now be more error proof
- Minor bug fixes

**Comment by chrispahm** [comment] 2019-03-29 10:48
Until then, you should be fine by just replacing your `linter.js` with the one I attached.
[linter.zip](https://github.com/chrispahm/linter-gams/files/3022245/linter.zip)

**Comment by iamkucuk** [comment] 2019-03-29 10:49
> Alright, I was expecting it's the `fileStem` option, because at this very moment we are experiencing the same error on a computer with GAMS 24.4.
> I hope that option can be safely deleted, I will do some test and then publish an update.
> 
> The following things are likley to change
> 
> * The fileStem option: It looks like this was introduced with GAMS 25.0, so removing it should resolve your issue
> * There was a small typo: Usually in scenarios like this, you should see a popup window where it shows you the error that you see in the console screenshot you appended above. That typo was making sure that popup never displays
> * I rewrote the code that searches for GAMS installations on your computer, that should now be more error proof
> * Minor bug fixes

I tried with latest gams version too and with no luck.

**Comment by chrispahm** [comment] 2019-03-29 12:30
> I tried the file you shared. It works like a charm! I wouldn't expect this extension works that perfectly :) Well thought, well done mate!

Glad to hear that you like it! 😍 
I just pushed a minor patch, it would be nice if you could do the update and check if everything still works correctly.

**Comment by iamkucuk** [comment] 2019-03-30 16:56
> 
> 
> > I tried the file you shared. It works like a charm! I wouldn't expect this extension works that perfectly :) Well thought, well done mate!
> 
> Glad to hear that you like it! 😍
> I just pushed a minor patch, it would be nice if you could do the update and check if everything still works correctly.

Update here! 

The patch seems like a good fix!

However, gams view get stuck sometimes switching between result window and code window (by window i mean the side window). It also may get stuck when a variable or set or parameter selected (by stuck I mean it won't show any other sets or parameters etc. and also doesn't switch to results too.)

**Comment by chrispahm** [comment] 2019-03-31 12:05
Alright, 
the behavior you are describing is a known bug. For now, the best workaround is to do a „reload“ (ctrl-shift-p, then type reload and enter) once you realize that the sidebar isn’t updating anymore. 

The error you may observe in the developer console says something along the lines “cannot remove element...”, and is thrown by Vue.js. I don’t manually add/remove elements to the DOM, so I guess what happens is that Vue is flooded by update events when typing/clicking/switching windows. I already implemented a debounce method, so the update is called every 250ms max. But that didn’t seem to suffice... 

If you’re interested in having a deeper look, I’d appreciate your help.
Best
Christoph

**Comment by chrispahm** [comment] 2019-04-01 07:44
@iamkucuk I started fiddling around, and found a couple of places where the actual `updateVue` function was called instead of the debounced version of it. Also, the template HTML had a couple of `v-show` lines that should have been `v-if`.

I don't know how familiar you are with Git, you can try out these changes by checking out the `updateVue` branch, else you might just replace the attached files.
[gams-view.zip](https://github.com/chrispahm/linter-gams/files/3028209/gams-view.zip)

**Comment by iamkucuk** [comment] 2019-04-01 07:55
> 
> 
> Alright,
> the behavior you are describing is a known bug. For now, the best workaround is to do a „reload“ (ctrl-shift-p, then type reload and enter) once you realize that the sidebar isn’t updating anymore.
> 
> The error you may observe in the developer console says something along the lines “cannot remove element...”, and is thrown by Vue.js. I don’t manually add/remove elements to the DOM, so I guess what happens is that Vue is flooded by update events when typing/clicking/switching windows. I already implemented a debounce method, so the update is called every 250ms max. But that didn’t seem to suffice...
> 
> If you’re interested in having a deeper look, I’d appreciate your help.
> Best
> Christoph

Sure, I would like to offer my help :)

**Comment by iamkucuk** [comment] 2019-04-01 07:55
> 
> 
> > Alright,
> > the behavior you are describing is a known bug. For now, the best workaround is to do a „reload“ (ctrl-shift-p, then type reload and enter) once you realize that the sidebar isn’t updating anymore.
> > The error you may observe in the developer console says something along the lines “cannot remove element...”, and is thrown by Vue.js. I don’t manually add/remove elements to the DOM, so I guess what happens is that Vue is flooded by update events when typing/clicking/switching windows. I already implemented a debounce method, so the update is called every 250ms max. But that didn’t seem to suffice...
> > If you’re interested in having a deeper look, I’d appreciate your help.
> > Best
> > Christoph
> 
> Sure, I would like to offer my help :)

I will look into it ASAP!

**Comment by chrispahm** [comment] 2019-04-02 12:21
@iamkucuk did you get the chance to have a look yet?

**Comment by chrispahm** [comment] 2019-04-10 10:10
Short update on this.
I could still reproduce the error when I am deleting text using backspace.
This is caused by a bug in Atom where the event fired from the text deletion falsely returns the `textChanged` property with `false`. 
https://github.com/atom/atom/issues/11870

In earlier days of this plugin, I had a small section in the `README` of how you can hack your way around this:

`Uncaught TypeError: Cannot read property 'removeChild' of null`
This error occurs frequently and is very hard to track down. However, for the time being, the following workaround exists:
Navigate to the installation directory of the `linter-gams` package. On Windows, the following will most likely work:
`%USERPROFILE%\.atom\packages\linter-gams\node_modules\vue\dist`
In that folder, open the file `vue.common.js`, and change the following code from line 1316
```js
function remove(el) {
  el.parentNode.removeChild(el);
}
```
to
```js
function remove(el) {
  if (!inDoc(el)) return false;
  el.parentNode.removeChild(el);
}
```

I will continue to have a look at this, though.

**Comment by iamkucuk** [comment] 2019-04-10 10:14
Sorry mate my finals are finally over. That's why I couldn't manage to look into it. I can take a look this week.

**Comment by chrispahm** [comment] 2019-05-16 20:23
Hey there,
I finally figured out how to upgrade Vue.js (the main underlying framework for the sidebar) to the latest version in `linter-gams`. Since then, I could not reproduce the sidebar updating issue anymore. Also, the general performance seems to be way better. I'd appreciate if you could check as well 🙏

**Comment by iamkucuk** [comment] 2019-05-16 20:41
> Hey there,
> I finally figured out how to upgrade Vue.js (the main underlying framework for the sidebar) to the latest version in `linter-gams`. Since then, I could not reproduce the sidebar updating issue anymore. Also, the general performance seems to be way better. I'd appreciate if you could check as well 🙏

Hey Chris!

Sorry for the late responses. I'm flooded with the lectures and upcoming exams right now so sorry I couldn't help you out.

However, the update seems perfect! The sidebar is working as it should be. Great job mate it works like a charm!

Will certainly update you if anything comes up. I'm grateful and appreciate for the work you've done. 🙏🙏

**Comment by chrispahm** [comment] 2019-05-17 06:49
Alright, thank for the feedback! I will close this issue then, please re-open or open a new one if the problem persists.

**Closed by chrispahm** 2019-05-17 06:49 UTC
